# Generated by Django 6.0.3 on 2026-04-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='footprint_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='已探索古建数'),
        ),
        migrations.AddField(
            model_name='user',
            name='influence_power',
            field=models.PositiveIntegerField(default=0, verbose_name='影响力值'),
        ),
        migrations.AddField(
            model_name='user',
            name='level_num',
            field=models.PositiveSmallIntegerField(default=1, help_text='对应 UserProfile 侧边栏 "二级·营造生" 中的数字', verbose_name='等级数字'),
        ),
        migrations.AddField(
            model_name='user',
            name='level_title',
            field=models.CharField(default='入门学徒', help_text='如：营造生、营造师、大匠', max_length=50, verbose_name='等级称号'),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_correct_count',
            field=models.PositiveIntegerField(default=0, verbose_name='答题正确数'),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_total_count',
            field=models.PositiveIntegerField(default=0, verbose_name='答题总数'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('reply', '回复通知'), ('announcement', '官方公告'), ('badge', '勋章通知'), ('reward', '奖励通知')], default='announcement', max_length=20, verbose_name='通知类型')),
                ('unread', models.BooleanField(db_index=True, default=True, verbose_name='是否未读')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发送时间')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='触发用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '通知消息',
                'verbose_name_plural': '通知消息列表',
                'db_table': 'users_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='奖励名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('reward_type', models.CharField(choices=[('coupon', '优惠券'), ('badge', '专属勋章'), ('other', '其他奖励')], default='other', max_length=20, verbose_name='奖励类型')),
                ('expires_at', models.DateField(blank=True, help_text='仅优惠券类奖励需填写', null=True, verbose_name='有效期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发放时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户奖励',
                'verbose_name_plural': '用户奖励列表',
                'db_table': 'users_reward',
                'ordering': ['-created_at'],
            },
        ),
    ]
