# Generated by Django 6.0.3 on 2026-04-04 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monuments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='正确答案')),
                ('distractor_a', models.CharField(max_length=200, verbose_name='干扰项 A')),
                ('distractor_b', models.CharField(max_length=200, verbose_name='干扰项 B')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/', verbose_name='参考图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('monument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='monuments.monument', verbose_name='关联古建')),
            ],
            options={
                'verbose_name': '题库题目',
                'verbose_name_plural': '题库题目列表',
                'db_table': 'quiz_question',
                'ordering': ['-created_at'],
            },
        ),
    ]
