# Generated by Django 6.0.3 on 2026-04-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0003_rename_title_monument_name_and_more'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='图选题主图，对应 StampDiscovery.quizOptions[].image', null=True, upload_to='quiz/', verbose_name='参考图'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='monument',
            field=models.ForeignKey(blank=True, help_text='题目归属的古建学习路径', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='monuments.monument', verbose_name='关联古建'),
        ),
        migrations.CreateModel(
            name='UserQuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='是否答对')),
                ('answered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='答题时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='quiz.quizquestion', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录列表',
                'db_table': 'quiz_user_record',
                'ordering': ['-answered_at'],
            },
        ),
    ]
