# Generated by Django 5.2.6 on 2026-04-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0004_monumentarticle_monumentarticlepage'),
        ('quiz', '0002_alter_quizquestion_image_alter_quizquestion_monument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='distractor_a',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='distractor_b',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='article_page',
            field=models.ForeignKey(blank=True, help_text='阅读完该页后弹出此题', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='monuments.monumentarticlepage', verbose_name='关联文章页'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='points',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='答对积分'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('single', '单选题'), ('multi', '多选题')], default='single', max_length=20, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='userquizrecord',
            name='points_earned',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='获得积分'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='题干中的参考图片（可选）', null=True, upload_to='quiz/', verbose_name='题目配图'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='monument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='monuments.monument', verbose_name='关联古建'),
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500, verbose_name='选项文字')),
                ('image', models.ImageField(blank=True, help_text='图选题时使用', null=True, upload_to='quiz/options/', verbose_name='选项图片')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.quizquestion', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '题目选项',
                'verbose_name_plural': '题目选项列表',
                'db_table': 'quiz_option',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='userquizrecord',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='user_selections', to='quiz.quizoption', verbose_name='选择的选项'),
        ),
    ]
