# Generated by Django 5.2.6 on 2026-04-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='forum/comment_images/', verbose_name='图片')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.comment', verbose_name='关联评论')),
            ],
            options={
                'verbose_name': '评论图片',
                'verbose_name_plural': '评论图片列表',
                'db_table': 'forum_comment_image',
                'ordering': ['sort_order'],
            },
        ),
    ]
