# Generated by Django 6.0.3 on 2026-04-11 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_commentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='heat_score',
            field=models.FloatField(db_index=True, default=0.0, verbose_name='热度分数'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='share_count',
            field=models.PositiveIntegerField(default=0, verbose_name='转发数'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='forum.comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞列表',
                'db_table': 'forum_comment_like',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='举报原因')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewed', '已审核'), ('dismissed', '驳回'), ('deleted', '已删除')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.comment', verbose_name='被举报评论')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_report_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核管理员')),
            ],
            options={
                'verbose_name': '评论举报',
                'verbose_name_plural': '评论举报列表',
                'db_table': 'forum_comment_report',
                'indexes': [models.Index(fields=['status'], name='forum_comme_status_c1ee11_idx'), models.Index(fields=['created_at'], name='forum_comme_created_8fcef6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForumInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', '点赞'), ('share', '转发')], max_length=10, verbose_name='交互类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='forum.forumpost', verbose_name='帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_interactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '论坛交互',
                'verbose_name_plural': '论坛交互列表',
                'db_table': 'forum_interaction',
                'indexes': [models.Index(fields=['user', 'post'], name='forum_inter_user_id_eb483f_idx'), models.Index(fields=['interaction_type'], name='forum_inter_interac_7c9300_idx')],
                'unique_together': {('user', 'post', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, verbose_name='举报原因')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewed', '已审核'), ('dismissed', '驳回'), ('deleted', '已删除')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.forumpost', verbose_name='被举报帖子')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_report_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核管理员')),
            ],
            options={
                'verbose_name': '帖子举报',
                'verbose_name_plural': '帖子举报列表',
                'db_table': 'forum_post_report',
                'indexes': [models.Index(fields=['status'], name='forum_post__status_1643b8_idx'), models.Index(fields=['created_at'], name='forum_post__created_192559_idx')],
            },
        ),
    ]
