# Generated by Django 6.0.3 on 2026-04-04 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interception_strength', models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='自动拦截强度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 监管配置',
                'verbose_name_plural': 'AI 监管配置',
                'db_table': 'system_ai_config',
            },
        ),
        migrations.CreateModel(
            name='AIInterceptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='如 submission、comment 等', max_length=50, verbose_name='内容类型')),
                ('content_id', models.PositiveIntegerField(verbose_name='内容 ID')),
                ('reason', models.TextField(verbose_name='拦截原因')),
                ('intercepted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='拦截时间')),
            ],
            options={
                'verbose_name': 'AI 拦截日志',
                'verbose_name_plural': 'AI 拦截日志',
                'db_table': 'system_ai_interception_log',
                'ordering': ['-intercepted_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_index', models.PositiveSmallIntegerField(db_index=True, verbose_name='节点编号')),
                ('load_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='负载百分比')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '节点状态',
                'verbose_name_plural': '节点状态记录',
                'db_table': 'system_node_status',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='敏感词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词库',
                'db_table': 'system_sensitive_word',
                'ordering': ['word'],
            },
        ),
    ]
