# Generated by Django 6.0.3 on 2026-04-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monuments', '0003_rename_title_monument_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='印章名称')),
                ('image', models.ImageField(blank=True, help_text='UserProfile 印章册中显示。未上传时展示 LockIcon', null=True, upload_to='stamps/', verbose_name='印章图片')),
                ('total_layers', models.PositiveSmallIntegerField(default=3, help_text='StampDiscovery 套色步骤总数，默认3层：素胎底框→朱砂描红→琉璃缀金', verbose_name='套色层数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monument', models.ForeignKey(blank=True, help_text='该印章隶属的古建学习路径', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamps', to='monuments.monument', verbose_name='关联古建')),
            ],
            options={
                'verbose_name': '印章',
                'verbose_name_plural': '印章列表',
                'db_table': 'stamps_stamp',
            },
        ),
        migrations.CreateModel(
            name='StampColorLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_index', models.PositiveSmallIntegerField(help_text='1=第一层，2=第二层，3=第三层', verbose_name='层级序号')),
                ('layer_name', models.CharField(help_text='如：第一层：素胎底框', max_length=100, verbose_name='层名称')),
                ('color', models.CharField(help_text='十六进制颜色，如 #e2e2e2', max_length=20, verbose_name='颜色值')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_layers', to='stamps.stamp', verbose_name='所属印章')),
            ],
            options={
                'verbose_name': '套色层',
                'verbose_name_plural': '套色层列表',
                'db_table': 'stamps_color_layer',
                'ordering': ['layer_index'],
                'unique_together': {('stamp', 'layer_index')},
            },
        ),
        migrations.CreateModel(
            name='UserStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_layers', models.PositiveSmallIntegerField(default=0, help_text='0=未收集，>0=已收集至少一层，=total_layers=完整印记', verbose_name='已解锁套色层数')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='首次收集时间')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='stamps.stamp', verbose_name='印章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stamps', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户印章',
                'verbose_name_plural': '用户印章册',
                'db_table': 'stamps_user_stamp',
                'unique_together': {('user', 'stamp')},
            },
        ),
    ]
