# Generated by Django 5.2.6 on 2026-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampcolorlayer',
            name='blend_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('multiply', 'Multiply（宣纸晕染）'), ('screen', 'Screen'), ('overlay', 'Overlay'), ('darken', 'Darken'), ('color-burn', 'Color Burn')], default='multiply', help_text='CSS mix-blend-mode，控制图层叠加效果', max_length=20, verbose_name='混合模式'),
        ),
        migrations.AddField(
            model_name='stampcolorlayer',
            name='svg_file',
            field=models.FileField(blank=True, help_text='上传独立的 SVG 文件，前端按顺序叠加渲染', null=True, upload_to='stamps/layers/', verbose_name='SVG 图层文件'),
        ),
        migrations.AlterField(
            model_name='stampcolorlayer',
            name='layer_index',
            field=models.PositiveSmallIntegerField(help_text='1=第一层，2=第二层，3=第三层…最多5层', verbose_name='层级序号'),
        ),
    ]
