# Generated by Django 6.0.3 on 2026-04-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(verbose_name='简介')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地理位置')),
                ('dynasty', models.CharField(blank=True, max_length=100, verbose_name='朝代')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='monuments/covers/', verbose_name='封面图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '古建条目',
                'verbose_name_plural': '古建条目列表',
                'db_table': 'monuments_monument',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='正文摘要')),
                ('image', models.ImageField(blank=True, null=True, upload_to='submissions/', verbose_name='配图')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=20, verbose_name='审核状态')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('feedback', models.TextField(blank=True, verbose_name='审核反馈建议')),
            ],
            options={
                'verbose_name': '用户投稿',
                'verbose_name_plural': '用户投稿列表',
                'db_table': 'monuments_submission',
                'ordering': ['-time'],
            },
        ),
    ]
