# Generated by Django 6.0.3 on 2026-04-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='monument',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='description',
        ),
        migrations.AddField(
            model_name='monument',
            name='desc',
            field=models.CharField(blank=True, help_text='用于卡片简短展示，对应 building.desc', max_length=500, verbose_name='简介摘要'),
        ),
        migrations.AddField(
            model_name='monument',
            name='era',
            field=models.CharField(blank=True, help_text='如：唐大中十一年 (857年)', max_length=150, verbose_name='建造年代'),
        ),
        migrations.AddField(
            model_name='monument',
            name='full_desc',
            field=models.TextField(blank=True, help_text='用于 Modal 档案详情，对应 building.fullDesc', verbose_name='详细描述'),
        ),
        migrations.AddField(
            model_name='monument',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='monument',
            name='structure_type',
            field=models.CharField(blank=True, help_text='如：殿堂式木构、楼阁式木塔、重檐庑殿顶', max_length=100, verbose_name='结构类型'),
        ),
        migrations.CreateModel(
            name='ArticleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='正文摘要')),
                ('image', models.ImageField(blank=True, null=True, upload_to='submissions/', verbose_name='配图')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=20, verbose_name='审核状态')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('feedback', models.TextField(blank=True, help_text='对应前端"输入审核反馈建议..."输入框', verbose_name='审核反馈建议')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_submissions', to=settings.AUTH_USER_MODEL, verbose_name='投稿人')),
                ('monument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_submissions', to='monuments.monument', verbose_name='关联古建')),
            ],
            options={
                'verbose_name': '投稿文章',
                'verbose_name_plural': '投稿文章列表',
                'db_table': 'monuments_article_submission',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='UserMonumentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已解锁')], db_index=True, default='pending', max_length=20, verbose_name='探索状态')),
                ('category_type', models.CharField(choices=[('palace', '宫廷建筑'), ('garden', '园林景观'), ('folk', '民居建筑'), ('other', '其他')], default='other', help_text='用于 UserProfile 足迹分类统计', max_length=20, verbose_name='建筑分类')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='monuments.monument', verbose_name='古建')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monument_progresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户探索进度',
                'verbose_name_plural': '用户探索进度',
                'db_table': 'monuments_user_progress',
                'unique_together': {('user', 'monument')},
            },
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
