# Generated by Django 5.2.6 on 2026-04-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0003_rename_title_monument_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('monument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='monuments.monument', verbose_name='关联古建')),
            ],
            options={
                'verbose_name': '古建详细文章',
                'verbose_name_plural': '古建详细文章',
                'db_table': 'monuments_article',
            },
        ),
        migrations.CreateModel(
            name='MonumentArticlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveSmallIntegerField(verbose_name='页码')),
                ('content', models.TextField(help_text='支持 HTML 富文本', verbose_name='页面内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='monuments.monumentarticle', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '文章页',
                'verbose_name_plural': '文章页列表',
                'db_table': 'monuments_article_page',
                'ordering': ['page_number'],
                'unique_together': {('article', 'page_number')},
            },
        ),
    ]
