# Generated by Django 6.0.3 on 2026-04-04 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoCreationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='对应 coCreations.title 和 form.name', max_length=200, verbose_name='筑品名称')),
                ('material', models.CharField(choices=[('原木', '原木'), ('青砖', '青砖'), ('石材', '石材'), ('金属', '金属')], default='原木', max_length=20, verbose_name='主材')),
                ('desc', models.TextField(help_text='对应 form.desc "描述你的灵感来源与设计理念..."', verbose_name='创意描述')),
                ('cover', models.ImageField(blank=True, help_text='对应 coCreations.image 瀑布流展示图', null=True, upload_to='cocreation/covers/', verbose_name='封面图')),
                ('featured', models.BooleanField(default=False, help_text='对应 coCreations.featured（"本周精选"标签）', verbose_name='本周精选')),
                ('likes', models.PositiveIntegerField(default=0, help_text='对应 coCreations.likes "1.2k"', verbose_name='点赞数')),
                ('status', models.CharField(choices=[('submitted', '待审核'), ('reviewing', '初审中'), ('sampling', '打样中'), ('producing', '试产中'), ('adopted', '已采纳'), ('rejected', '已驳回')], db_index=True, default='submitted', max_length=20, verbose_name='进度状态')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, help_text='对应 myProgress.percent，范围 0-100，前端进度条展示', verbose_name='官方反馈进度(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocreations', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
            options={
                'verbose_name': '共创筑品',
                'verbose_name_plural': '共创筑品列表',
                'db_table': 'cocreation_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoCreationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cocreation/images/', verbose_name='灵感图')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cocreation.cocreationitem', verbose_name='关联筑品')),
            ],
            options={
                'verbose_name': '筑品灵感图',
                'verbose_name_plural': '筑品灵感图列表',
                'db_table': 'cocreation_image',
                'ordering': ['sort_order'],
            },
        ),
    ]
